### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#116]
```shell
$ ethereumjs
INFO [06-01|17:47:12] Data directory:/ethereumjs/chaindata
INFO [06-01|17:47:12] Initializing Ethereumjs client...
INFO [06-01|17:47:12] Fast sync mode
INFO [06-01|17:47:12] Connecting to network: mainnet
INFO [06-01|17:47:12] Latest local block: number=756736 td=4760424299033370527 hash=b04c06a9...
INFO [06-01|17:47:12] Synchronizing blockchain...
INFO [06-01|17:47:12] Started rlpx server.
INFO [06-01|17:47:12] Started libp2p server.
INFO [06-01|17:47:14] Listener up transport=rlpx url=enode://196b9d06b0c153ec8ed78455c7ecb67d661f5279569d0a1ea9ec3afe8d670692d0da57ea781902e14409364f065c6c275c63f9b57e446fc482fa24be1fe4ed76@[::]:30303
INFO [06-01|17:47:14] Listener up transport=libp2p url=/p2p-circuit/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Listener up transport=libp2p url=/p2p-circuit/ip4/127.0.0.1/tcp/50580/ws/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Listener up transport=libp2p url=/ip4/127.0.0.1/tcp/50580/ws/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Started eth service.
ERROR [06-01|17:48:44] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:431:19)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at Peer._sendMessage (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:406:22)
    at Peer._sendPong (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:441:14)
    at Peer._handleMessage (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:349:22)
    at Peer._parsePacketContent (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:222:34)
    at Socket.<anonymous> (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:162:31)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
```

This error is thrown repeatedly during a normal sync run and needs some further investigation.

**Comment by holgerd77** [comment]
Also got this now with a more verbose communication output around:

```shell
  devp2p:rlpx disconnect from 35.192.55.65:30303, reason: 16 +0ms
  devp2p:eth Received STATUS message from 128.199.64.114:30306: : [V:63, NID:1004, TD:2.101924180470637e+44, BestH:caf1900339a1e4d5a99370a3cb904a659872793c8aff7f4cb9d59b8fd68bcac2, GenH:99608136d8e14bb9a5e0f605b6463f3080b2abee7a48d97a62c832a9a12eafd2] +37ms
  devp2p:rlpx refill connections.. queue size: 6, open slots: 12 +3ms
  devp2p:rlpx 128.199.64.114:30306 disconnect, reason: 0 +1ms
  devp2p:eth Received STATUS message from 165.227.5.84:28657: : [V:63, NID:1, TD:13314525, BestH:edd631e988f1eab4730da3c90fc142acf2860a8dc827c9bbf2ca287df72276d6, GenH:16b48c1e6d72cf2648ac392e400c5bf22bf824007cdbb491ef2bca75c40f6d6a] +33ms
ERROR [06-01|18:01:27] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
... will leave the stack trace aside here
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
  devp2p:rlpx refill connections.. queue size: 6, open slots: 13 +123ms
  devp2p:rlpx 3.222.101.82:30303 disconnect, reason: undefined +0ms
  devp2p:rlpx handshake with 52.32.79.139:30303 was successful (peer eip8 ack) +4ms
```
