### ISSUE TITLE
Error: Request timed out after 5000ms

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#117]
Also some common and repeated output which interrupts the normal sync information flow:

```shell
INFO [06-01|17:49:58] Listener up transport=libp2p url=/p2p-circuit/ipfs/QmSNBxworMfvyHjdBZrycRyUSUGjvMgtDFEHHJV4JoFLjJ
INFO [06-01|17:49:58] Listener up transport=libp2p url=/p2p-circuit/ip4/127.0.0.1/tcp/50580/ws/ipfs/QmSNBxworMfvyHjdBZrycRyUSUGjvMgtDFEHHJV4JoFLjJ
INFO [06-01|17:49:58] Listener up transport=libp2p url=/ip4/127.0.0.1/tcp/50580/ws/ipfs/QmSNBxworMfvyHjdBZrycRyUSUGjvMgtDFEHHJV4JoFLjJ
INFO [06-01|17:49:58] Started eth service.
ERROR [06-01|17:51:35] Error: Request timed out after 5000ms
    at Timeout._onTimeout (/ethereumjs-client/lib/net/protocol/boundprotocol.js:129:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

This should be caught and channeled to the `debug` level logger output.

**Comment by holgerd77** [comment]
Note: at least partially solved by https://github.com/ethereumjs/ethereumjs-client/pull/133, if no significant further observations on this during client runs we might be able to close here.

**Comment by holgerd77** [comment]
Will close this for now.
