### ISSUE TITLE
With latest commit RPC calls are failing 

### ISSUE THREAD

**Issue by bit-warrior** [ethereumjs/ethereumjs-client#42]
#### Description
@vpulim   With latest commit RPC calls are failing 

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1b4", true],"id":1}' -H "Content-Type: application/json" http://127.0.0.1:8545|jq

ERROR [08-03|00:09:37] uncaughtException: Cannot read property 'getBlock' of undefined
TypeError: Cannot read property 'getBlock' of undefined
    at Eth.getBlockByNumber (/softwares/ethereumjs-client/lib/rpc/modules/eth.js:15:17)
    at Eth.getBlockByNumber (/softwares/ethereumjs-client/lib/rpc/validation.js:30:7)
    at Method.execute (/softwares/ethereumjs-client/node_modules/jayson/lib/method.js:123:20)
    at /softwares/ethereumjs-client/node_modules/jayson/lib/server/index.js:295:12
    at maybeParse (/softwares/ethereumjs-client/node_modules/jayson/lib/server/index.js:418:5)
    at Server.call (/softwares/ethereumjs-client/node_modules/jayson/lib/server/index.js:231:3)
    at /softwares/ethereumjs-client/node_modules/jayson/lib/utils.js:151:14
    at /softwares/ethereumjs-client/node_modules/lodash/lodash.js:10050:25
    at /softwares/ethereumjs-client/node_modules/jayson/lib/utils.js:117:7
    at Object.Utils.JSON.parse (/softwares/ethereumjs-client/node_modules/jayson/lib/utils.js:254:3)

#### Possible Implementation

https://github.com/ethereumjs/ethereumjs-client/blob/7d4926b086d6cf3f10382f6bdc16815125d7d909/bin/cli.js#L93

 runRpcServer(node.chain, options)

node does not have a chain object but nodes.services[0] will have.

and other problem blockchain/chain,js does not have gteBlock function

**Comment by vpulim** [comment]
@bit-warrior Fixed in #43.
