### ISSUE TITLE
Error on NPM Install

### ISSUE THREAD

**Issue by aunyks** [ethereumjs/ethereumjs-client#48]
#### Description
I've been receiving errors when cloning this repository and trying to install dependencies. The same error shows when installing with `yarn` as well.

Node: v8.0.0
NPM: v5.8.0

```
> npm i
events.js:182░░░░░░⸩ ⠹ extract:qheap: sill extract winston-transport@4.2.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:220:12)
    at PassThrough.Writable.write (_stream_writable.js:271:5)
    at PassThrough.Writable.end (_stream_writable.js:528:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:182░░░░░░⸩ ⠧ extract:read-pkg-up: sill extract typedarray@0.0.6
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:220:12)
    at PassThrough.Writable.write (_stream_writable.js:271:5)
    at PassThrough.Writable.end (_stream_writable.js:528:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:182░░░░░░⸩ ⠼ extract:async: sill extract js-sha3@0.3.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:220:12)
    at PassThrough.Writable.write (_stream_writable.js:271:5)
    at PassThrough.Writable.end (_stream_writable.js:528:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:182░░░░░░⸩ ⠋ extract:is-date-object: sill extract inherits@2.0.3
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:220:12)
    at PassThrough.Writable.write (_stream_writable.js:271:5)
    at PassThrough.Writable.end (_stream_writable.js:528:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
WARN tar ENOENT: no such file or directory, scandir '/Users/aunyks/dev/ethjs/node_modules/.staging/json-schema-16847c42/draft-03'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/nyc-645405cc/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/json-schema-16847c42/draft-03/examples/calendar'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/nyc-645405cc/CHANGELOG.md'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/json-schema-16847c42/draft-03/examples/card'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/json-schema-16847c42/draft-03/examples/geo'
WARN tar ENOENT: no such file or directory, open '/Users/aunyks/dev/ethjs/node_modules/.staging/json-schema-16847c42/draft-03/examples/interfaces'
npm ERR! cancel after 1 retries!
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:220:12)
    at PassThrough.Writable.write (_stream_writable.js:271:5)
    at PassThrough.Writable.end (_stream_writable.js:528:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
```

#### Possible Implementation
N/A

#### UI
CLI

#### Reference Implementations / Links
N/A

**Comment by jwasinger** [comment]
NodeJS/NPM version?

**Comment by aunyks** [comment]
@jwasinger 
Node: v8.0.0
NPM: v5.8.0

**Comment by jwasinger** [comment]
Huh.. that's very strange.  I would suggest setting up a fresh environment (VM) and trying to see if you get the same error.

I used Node v8.10.0 and Npm 3.5.2 and couldn't reproduce this.

**Comment by aunyks** [comment]
Will do. Thanks for taking a look

**Comment by vpulim** [comment]
@aunyks Were you able to reproduce this error after setting up a fresh node environment? If not, I’ll close out this issue.

**Comment by aunyks** [comment]
@vpulim I'm not sure how to set up a fresh Node env? Do you have a resource explaining how to do so?

**Comment by aunyks** [comment]
Thanks @jwasinger. I'll close right now and do some more troubleshooting then reopen if I'm still having trouble.
