### ISSUE TITLE
RLPx uncaughtException

### ISSUE THREAD

**Issue by unsol** [ethereumjs/ethereumjs-client#96]
I left EthereumJS, attached to Goerli, running overnight (no RPC this time. Launched only with "ethereumjs --network goerli"), and the client crashed. 

Here are the steps I took to install the client: 
1. sudo apt-get install build-essential
2. Follow the EthStats installation instructions steps one, and two
3. curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | sudo bash
4. export NVM_DIR=”${XDG_CONFIG_HOME/:-$HOME/.}nvm”
5. [ -s “$NVM_DIR/nvm.sh” ] && \. “$NVM_DIR/nvm.sh”
6. close your terminal (or end your session), then start a new one. Seriously. This is a required step.
7. nvm install node
8. nvm use node
9. npm -g install ethereumjs-client
10. tmux new -s ethereumjs
11. ethereumjs –network goerli

This was just before the crash:

`INFO [02-20|23:51:39] Imported blocks count=15 number=114354 hash=1ca26f03... peers=2`
`INFO [02-20|23:51:41] Synchronized`

First error:
`ERROR [02-21|00:04:10] uncaughtException: Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
    at RLPx.rlpx.on (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/lib/net/server/rlpxserver.js:213:34)
    at RLPx.emit (events.js:197:13)
    at Peer.peer.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/index.js:202:34)
    at Peer.emit (events.js:197:13)
    at Socket.Peer._socket.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/peer.js:59:42)
    at Socket.emit (events.js:202:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

Second/last error:
`ERROR [02-21|00:04:10] uncaughtException: Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
    at RLPx.rlpx.on (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/lib/net/server/rlpxserver.js:213:34)
    at RLPx.emit (events.js:197:13)
    at Peer.peer.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/index.js:202:34)
    at Peer.emit (events.js:197:13)
    at Socket.Peer._socket.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/peer.js:59:42)
    at Socket.emit (events.js:202:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

**Comment by vpulim** [comment]
Thanks again @unsol. These bug reports are extremely helpful. Keep 'em coming! 😄 

A fix is on the way.

**Comment by unsol** [comment]
Hey you're most welcome! Thank you for being so speedy! I'll clone the latest from master.

**Comment by vpulim** [comment]
Out of curiosity, how long does it take you to sync the complete ``goerli`` blockchain? It takes me about 8 minutes right now on my 150Mbps broadband  connection.

**Comment by unsol** [comment]
Oh! My apologies for the non-response. I'm currently synching Goerli, and I'm about 27,500 blocks in after a minute or two.
