### ISSUE TITLE
ECIES._decryptMessage AssertionError loop

### ISSUE THREAD

**Issue by unsol** [ethereumjs/ethereumjs-client#99]
Here are the steps I took to get the client running

1. Delete the old source folder
2. Cloned master commit f84ea6b8cb4d0a1785b89a2040682681475073fd (Merge pull request #97 from ethereumjs/fix-rlpx-error)
3. npm i
4. ./cli.js --network goerli --identity "Blockchains LLC EthereumJS" --ethstats "BlockchainsLLC:TheActualPassword@https://stats.goerli.net"

After the first round of errors, I ran the client without the ethstats option, and received the same error.
`./cli.js --network goerli --identity "Blockchains LLC EthereumJS"`

Finally, I stripped everything out, and still got the assertion error.
`./cli.js --network goerli`

After starting the client, it synchronized, then seemed to hang:
`INFO [02-21|18:52:46] Started eth service.`
`INFO [02-21|18:53:17] Imported blocks count=10 number=118936 hash=0da79868... peers=1`
`INFO [02-21|18:53:18] Synchronized`

After maybe 1-2 minutes, I received this error (but the client did NOT crash):

`ERROR [02-21|18:55:03] uncaughtException: Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null                   
    at RLPx.rlpx.on (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/lib/net/server/rlpxserver.js:213:34)
    at RLPx.emit (events.js:197:13)                                                                       at Peer.peer.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/n
ode_modules/ethereumjs-devp2p/lib/rlpx/index.js:202:34)                                                   at Peer.emit (events.js:197:13)
    at Socket.Peer._socket.on.err (/home/ubuntu/.nvm/versions/node/v11.10.0/lib/node_modules/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/peer.js:59:42)
    at Socket.emit (events.js:197:13)                                                                     at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

The client then hangs again for 1-2 minutes, then repeats that error (without crashing). This goes on until you manually interrupt. No other messages pop up between the errors.

**Comment by vpulim** [comment]
Is that the correct stack trace? I don't see a ``ECIES._decryptMessage AssertionError``?

**Comment by unsol** [comment]
Ahh.... nope! Sure is not! Haha! My bad.

`ERROR [02-21|19:19:21] AssertionError [ERR_ASSERTION]: should have valid tag: 719cc94b1735f34c2044fac3fdbad950aa6c1d42a3df238ec1a5560b2f420297 / 123832009579a77b5e4a0beb778ff874db02b6d1638e1d91ff3a0e6f4ed3073a
    at new AssertionError (internal/assert/assertion_error.js:396:11)
    at Object.assertEq (/home/ubuntu/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/util.js:70:11)
    at ECIES._decryptMessage (/home/ubuntu/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/ecies.js:106:10)
    at ECIES.parseAuthPlain (/home/ubuntu/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/ecies.js:161:28)
    at ECIES.parseAuthEIP8 (/home/ubuntu/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/ecies.js:204:10)
    at Socket.Peer._socket.on.data (/home/ubuntu/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/rlpx/peer.js:86:34)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)`

**Comment by vpulim** [comment]
No problem 😄 Ok, so that just looks like a peer sending bad messages. Those can be ignored and should probably only show them in debug mode. The reason nothing else is happening is likely due to this issue: https://github.com/ethereumjs/ethereumjs-client/issues/98

I'm going to assign this a low priority for now since it's not a critical error.

**Comment by unsol** [comment]
Sounds good. Thank you!

**Comment by holgerd77** [comment]
Haven't seen this error for quite a while, will close, feel free to reopen if still persists.

**Comment by unsol** [comment]
No news is good news! Thanks for the update.
